### ISSUE TITLE
Commit 4186ce3 has 17 failed tests

### ISSUE THREAD

**Issue by david-pfx** [Auroriax/PuzzleScriptPlus#85] opened 2023-02-27 05:19 UTC
I simply cloned the repo and ran the tests. Multiple times, on multiple browsers, using the local python server.

I get 17 failed tests. They look like capitalisation problems.

**Comment by david-pfx** [comment] 2023-02-28 06:18
Actually, the Danish Pastry test fails because of a bug in parser.js at line 1260, introduced by Tom H 17 months ago.
I expect to fix this and the capitalisation issues in my work on #23.

**Comment by Auroriax** [comment] 2023-02-28 07:24
Duplicate of #31, closing.

**Closed by Auroriax** 2023-02-28 07:24 UTC
