### ISSUE TITLE
New commands TITLE and STATUS

### ISSUE THREAD

**Issue by david-pfx** [Auroriax/PuzzleScriptPlus#100] opened 2023-04-17 07:14 UTC
The `TITLE <text>` command puts `<text>` into the title line, above the game grid.
The `STATUS <text>` command puts `<text>` into the status line, below the game grid.

Nothing special, just there for developers who want to be more chatty than `MESSAGE` conveniently allows.

**Comment by Auroriax** [comment] 2023-04-25 14:55
Duplicate of #49.

**Closed by Auroriax** 2023-04-25 14:55 UTC
